---
- name: Create Horovod workers
  hosts: all
  become: yes
  vars_files:
    - ./group_vars/variables.yml
  roles:
    - docker
    - consul_worker
    - horovod_worker
    - prometheus_node_exporter
    - prometheus_cadvisor

