---
- name: Create node-exporter container
  become: true
  community.docker.docker_container:
    name: "{{ node_exporter_service_name }}"
    recreate: yes
    restart: yes
    restart_policy: always
    privileged: yes
    command: "{{ node_exporter_args }}"
    detach: true
    image: "{{ node_exporter_image }}"
    network_mode: host
    pid_mode: host
    state: started
    volumes:
      - "/:/host:ro,rslave"
      # - "/var/run/dbus/system_bus_socket:/var/run/dbus/system_bus_socket:ro"

