---

- name: Create a directory if it does not exist
  ansible.builtin.file:
    path: /etc/consul.d
    state: directory
    mode: '0755'

- name: Template a services_master.json to /etc/file.conf
  #vars:
  #  node_name : "{{ NODE_NAME }}"
  ansible.builtin.template:
    src: templates/services_master.json.j2
    dest: /etc/consul.d/services.json
  when: node_name == "Horovod_master"

- name: Template a services_worker.json to /etc/file.conf
  #vars:
  #  node_name : "{{ NODE_NAME }}"
  ansible.builtin.template:
    src: templates/services_worker.json.j2
    dest: /etc/consul.d/services.json
  when: node_name == "Horovod_worker"
    
- name: Template a consul.hcl to /etc/file.conf
  ansible.builtin.template:
    src: templates/consul.hcl.j2
    dest: /etc/consul.d/consul.hcl


- name: Create Consul agent container
  become: true
  community.docker.docker_container:
    name: "consul_agent"
    recreate: yes
    restart: yes
    restart_policy: always
    privileged: yes
    command: "{{ consul_agent_args }}"
    detach: true
    image: "{{ consul_image }}"
    network_mode: host
    state: started
    volumes:
      - "/tmp/consul:/consul/data"
      - "/etc/consul.d:/consul/config"

